"""
PROCESS SIGNIFICANCE:
Aggregates analytical findings into scientific diagnostic reports.
"""

import argparse
import pandas as pd
import os
from src.common import load_config, ensure_dir

def collect_table(path, label):
    try:
        df = pd.read_csv(path)
        return df, True
    except Exception as e:
        return pd.DataFrame({"error": [str(e)]}), False

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True)
    parser.add_argument("--fold", type=int, required=True)
    args = parser.parse_args()

    cfg = load_config(args.config)
    dataset = cfg['dataset']['name']

    rep_dir = f"results/reports/{dataset}/fold_{args.fold}"
    tab_dir = f"results/tables/{dataset}/fold_{args.fold}"
    paper_ready_dir = "results/paper_ready"
    ensure_dir(rep_dir)
    ensure_dir(paper_ready_dir)

    # Collect all tables
    tables = {
        "Dataset Statistics":         f"results/tables/{dataset}/dataset_stats.csv",
        "Graph Statistics":           f"{tab_dir}/graph_stats.csv",
        "E_pre Edges":                f"{tab_dir}/E_pre_train_pruned.csv",
        "E_sim Edges":                f"{tab_dir}/E_sim_train.csv",
        "E_co Edges":                 f"{tab_dir}/E_co_train.csv",
        "DAG Audit":                  f"{tab_dir}/dag_audit.csv",
        "Eco Audit":                  f"{tab_dir}/eco_audit.csv",
        "QMatrix Audit":              f"{tab_dir}/qmatrix_audit.csv",
        "Leakage Audit Log":          f"{tab_dir}/leakage_audit_log.csv",
        "Sparse Skill Profile":       f"{tab_dir}/sparse_skill_profile.csv",
        "Sparse Skill Strata Summary":f"{tab_dir}/sparse_skill_strata_summary.csv",
        "Sparse Skill Summary":       f"{tab_dir}/sparse_skill_summary.csv",
        "Edge Provenance":            f"{tab_dir}/edge_provenance.csv",
    }

    # Build diagnostic report Markdown
    md = f"# P0 Diagnostic Report — {dataset} fold {args.fold}\n\n"
    md += f"Generated by: report_generator.py\n\n"
    md += "---\n\n"

    all_ok = True
    for title, path in tables.items():
        df, ok = collect_table(path, title)
        if not ok:
            all_ok = False
        md += f"## {title}\n\n"
        if ok and not df.empty:
            md += df.head(20).to_markdown(index=False) + "\n\n"
            if len(df) > 20:
                md += f"*...{len(df)-20} more rows omitted...*\n\n"
        else:
            md += f"*Data unavailable or empty.*\n\n"
        md += "---\n\n"

    # Summary block
    md += "## Pipeline Summary\n\n"
    try:
        df_audit = pd.read_csv(f"{tab_dir}/leakage_audit_log.csv")
        for _, row in df_audit.iterrows():
            status_icon = "✅" if row['status'] == 'PASS' else "❌"
            md += f"- {status_icon} {row['check_name']}: **{row['status']}**\n"
    except:
        md += "- Leakage audit log not found.\n"

    with open(f"{rep_dir}/p0_diagnostic_report.md", "w", encoding="utf-8") as f:
        f.write(md)
    print(f"[report] Diagnostic report written: {rep_dir}/p0_diagnostic_report.md")

    # Zip outputs
    import shutil
    shutil.make_archive(
        base_name=f"{paper_ready_dir}/{dataset}_fold_{args.fold}_tables",
        format="zip",
        root_dir=tab_dir
    )
    shutil.make_archive(
        base_name=f"{paper_ready_dir}/{dataset}_fold_{args.fold}_figures",
        format="zip",
        root_dir=f"results/figures/{dataset}/fold_{args.fold}"
    )
    print(f"[report] Archives created in {paper_ready_dir}/")
    print(f"End-to-end P0 pipeline completed for {dataset} fold {args.fold}.")